import numpy
positions = [[14,14], [40,40]]
sizes = [3,3]
densities = [300, 200]
velocities = [[2,2], [-2,-2]]
behaviors = ['normal', 'normal']
colors = [
    'viridis',
    'plasma',
    'inferno',
    'cividis',
    'Greys',
    'Purples',
    'Blues',
    'Greens',
    'Oranges',
    'Reds',
    'YlOrBr',
    'YlOrRd',
    'OrRd',
    'PuRd',
    'RdPu',
    'BuPu',
    'GnBu',
    'PuBu',
    'YlGnBu',
    'PuBuGn',
    'BuGn',
    'YlGn',
    'binary',
    'gist_yarg',
    'gist_gray',
    'gray',
    'bone',
    'pink',
    'spring',
    'summer',
    'autumn',
    'winter',
    'cool',
    'Wistia',
    'hot',
    'afmhot',
    'gist_heat',
    'copper',
    'PiYG',
    'PRGn',
    'BrBG',
    'PuOr',
    'RdGy',
    'RdBu',
    'RdYlBu',
    'RdYlGn',
    'Spectral',
    'coolwarm',
    'bwr',
    'seismic',
    'twilight',
    'twilight_shifted',
    'hsv',
    'flag',
    'prism',
    'ocean',
    'gist_earth',
    'terrain',
    'gist_stern',
    'gnuplot',
    'gnuplot2',
    'CMRmap',
    'cubehelix',
    'brg',
    'gist_rainbow',
    'rainbow',
    'jet',
    'turbo',
    'nipy_spectral',
    'gist_ncar'
]